### PR TITLE
Implemented proper handling of absent files. Fixes #34

### LINKED ISSUE #34: no erros is input file does not exist
Steps:
```
$ git clone https://github.com/sevntu-checkstyle/methods-distance.git
....
$ cd methods-distance
$ mvn package
..........
$ java -jar methods-distance/target/methods-distance-1.0-SNAPSHOT-jar-with-dependencies.jar --generate-dsm --generate-dot methods-distance/src/main/java/com/github/sevntu/checkstyle/Main111111.java 
$ ll
total 68
drwxrwxr-x 7 rivanov rivanov 4096 Nov 17 11:02 ./
drwxrwxr-x 7 rivanov rivanov 4096 Sep 19 16:47 ../
-rw-rw-r-- 1 rivanov rivanov  983 Nov 17 10:53 appveyor.yml
drwxrwxr-x 2 rivanov rivanov 4096 Sep 19 16:47 config/
-rwxrwxr-x 1 rivanov rivanov 1031 Sep 19 16:47 fast-forward-merge.sh*
drwxrwxr-x 8 rivanov rivanov 4096 Nov 17 11:02 .git/
-rw-rw-r-- 1 rivanov rivanov  304 Sep 19 16:47 .gitignore
drwxrwxr-x 4 rivanov rivanov 4096 Nov 17 10:54 methods-distance/
drwxrwxr-x 4 rivanov rivanov 4096 Nov 17 10:54 methods-distance-web/
-rw-rw-r-- 1 rivanov rivanov 4831 Sep 19 16:47 pom.xml
-rw-rw-r-- 1 rivanov rivanov  131 Sep 19 16:47 Procfile
-rw-rw-r-- 1 rivanov rivanov 4791 Nov 17 11:02 README.md
-rw-rw-r-- 1 rivanov rivanov   79 Sep 19 16:47 system.properties
drwxrwxr-x 2 rivanov rivanov 4096 Nov 17 10:54 target/
-rw-rw-r-- 1 rivanov rivanov  923 Nov 17 10:53 .travis.yml
```

Expected: exception that file is not found and non-zero exit code .

### PR DESCRIPTION
**Pull request by alex-zuy**
please review

### CODE REVIEW

**Comment by romani** [comment]
It is not ok.
If will never write logic for all problems that could happen with files.
Checker or Treewalker or Module should fail with exception , all you need it to deliver it to user

**Comment by alex-zuy** [comment]
You are absolutely correct, but `Checker` violates this principle (it [catches IOException and logs it](https://github.com/checkstyle/checkstyle/blob/6f82844f83024fbec2194a17721a41e741bd6bb3/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L310) without rethrowing, wrapping, etc). That's what forced me to check file existence manually. Look`s like `Checker` need to be fixed in order fix issue #34 correctly.

**Comment by romani** [comment]
Please use fileMessages , it is not only logged.

**Comment by alex-zuy** [comment]
@romani , please review

**Pull request merged**
