### PR TITLE
infra: setup manual trigger for heroku deploy

### PR DESCRIPTION
**Pull request by nrmancuso**
From https://github.com/sevntu-checkstyle/methods-distance/pull/74#issuecomment-1469933987:

@nrmancuso , it would be awesome.
better to release when required, not on commit, as some commits are not functional changes for user.

### CODE REVIEW

**Comment by nrmancuso** [comment]
Direct link to deployment README: https://github.com/sevntu-checkstyle/methods-distance/blob/7068a3dba6944712d65e4271b4c36d4c1e761596/.circleci/README.md

**Comment by nrmancuso** [comment]
Link to workflow triggered manually as proof that changes work: https://app.circleci.com/pipelines/github/sevntu-checkstyle/methods-distance/10/workflows/8531b380-48f2-40d6-8495-7a3af45a115d

We still need to set API key in environment variables

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
it is not good that CI fails, deploy should not be triggered in PR.

**Comment by nrmancuso** [comment]
@romani see https://github.com/sevntu-checkstyle/methods-distance/pull/75#issuecomment-1469965967, CI is failing from missing API key. I triggered workflow manually (the only way to do it now), do you still want branch filter?

**Comment by romani** [comment]
We did not trigger it to let it fail.
Or it is feature of circleci to show all builds for commit? even they are manual

**Comment by nrmancuso** [comment]
@romani builds are on commit, and show up in PR if commit exists there

**Comment by romani** [comment]
key is regenerated at https://dashboard.heroku.com/account and deploy is passed .

**Comment by romani** [comment]
there is no free tier any more.

```
~/java/github/sevntu-checkstyle/methods-distance [master|✔] 
07:46 $ heroku ps:scale web=1 -a methods-distance
 ›   Warning: heroku update available from 7.69.1 to 8.0.4.
Scaling dynos... !
 ▸    Item Could not be Updated: The app owner has to subscribe to Eco to scale your dynos. Learn more at https://blog.heroku.com/new-low-cost-plans
```

I opened ticket on how to stay free - https://help.heroku.com/tickets/1240314?n=1

**Comment by romani** [comment]
https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq

>Open source programs: If you are a maintainer on an open-source project, and would like to request Heroku support for your project, contact the Salesforce Open Source Program office at ospo-heroku-credits@salesforce.com.

I sent request to it.

**Pull request merged**
