### PR TITLE
infra: migrate to CircleCI

### PR DESCRIPTION
**Pull request by nrmancuso**
Completes migration to CircleCI

We need HEROKU_API_KEY stored in env variables in project settings, see https://circleci.com/developer/orbs/orb/circleci/heroku for details

### CODE REVIEW

**Comment by romani** [comment]
Better to do this by GitHub action from master, more secure

**Comment by romani** [comment]
Or maybe be circleci have manual trigger from ui?

**Comment by nrmancuso** [comment]
Right now, this workflow will only run on merge to master, which is what travis was doing before. Also - I did not turn on building forked PRs for this repo. So we should be fine security-wise. We can make this workflow able to be triggered by UI only though, if you want.

**Comment by romani** [comment]
> We can make this workflow able to be triggered by UI only though, if you want.

@nrmancuso , it would be awesome.
better  to release when required, not on commit, as some commits are not functional changes for user.

**Pull request merged**
