### PR TITLE
Fixed tests that was failing on windows. Fixes #9

### LINKED ISSUE #9: Build fails on Windows
Project build fails on windows. Steps to reproduce:

1. Clone sources:
```
git clone git@github.com:sevntu-checkstyle/methods-distance.git
```
2. Enter folder `methods-distance-dsm`:
```
cd methods-distance-dsm
```
3. Compile project:
```
mvn package
```

Build output:
```
...
testRelativeOrderInconsistency(com.github.sevntu.checkstyle.analysis.OrderingTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.NullPointerException
        at com.github.sevntu.checkstyle.ordering.Ordering.getAllMethods(Ordering.java:264)
        at com.github.sevntu.checkstyle.ordering.Ordering.<init>(Ordering.java:41)
        at com.github.sevntu.checkstyle.analysis.MethodCallDependenciesCheckTestSupport.withDefaultConfigOrdering(MethodCallDependenciesCheckTestSupport.java:91)
        at com.github.sevntu.checkstyle.analysis.OrderingTest.testRelativeOrderInconsistency(OrderingTest.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error:
  testSeveralAccessors(com.github.sevntu.checkstyle.analysis.ClassDefinitionTest)
  testMethodCallInInitialization(com.github.sevntu.checkstyle.analysis.MethodCallDependencyCheckTest)
  testNotThisClassMethodCall(com.github.sevntu.checkstyle.analysis.MethodCallDependencyCheckTest)
  testMethodCallsInLambda(com.github.sevntu.checkstyle.analysis.MethodCallDependencyCheckTest)
  testSimpleDependency(com.github.sevntu.checkstyle.analysis.MethodCallDependencyCheckTest)
  testRecursiveMethod(com.github.sevntu.checkstyle.analysis.MethodCallDependencyCheckTest)
  testOverloadedMethods2(com.github.sevntu.checkstyle.analysis.MethodCallDependencyCheckTest)
  testMethodCallThroughMethodReference(com.github.sevntu.checkstyle.analysis.MethodCallDependencyCheckTest)
  testMethodSignatures(com.github.sevntu.checkstyle.analysis.MethodCallDependencyCheckTest)
  testAnonymousClasses(com.github.sevntu.checkstyle.analysis.MethodCallDependencyCheckTest)
  testVarargMethodCall(com.github.sevntu.checkstyle.analysis.MethodCallDependencyCheckTest)
  testAppearanceOrder(com.github.sevntu.checkstyle.analysis.MethodCallDependencyCheckTest)
  testGetterSetterRecognitionsWithCtors(com.github.sevntu.checkstyle.analysis.MethodDefinitionTest)
  testGetterSetterRecognition(com.github.sevntu.checkstyle.analysis.MethodDefinitionTest)
  testReordering(com.github.sevntu.checkstyle.analysis.OrderingReorderTest)
  testOverrideSplit1(com.github.sevntu.checkstyle.analysis.OrderingTest)
  testOverrideSplit2(com.github.sevntu.checkstyle.analysis.OrderingTest)
  testOverrideSplit3(com.github.sevntu.checkstyle.analysis.OrderingTest)
  testCallsBetweenDistantMethods(com.github.sevntu.checkstyle.analysis.OrderingTest)
  testOverloadSplit1(com.github.sevntu.checkstyle.analysis.OrderingTest)
  testOverloadSplit2(com.github.sevntu.checkstyle.analysis.OrderingTest)
  testAccessorsSplit(com.github.sevntu.checkstyle.analysis.OrderingTest)
  testDeclarationBeforeUsageCases(com.github.sevntu.checkstyle.analysis.OrderingTest)
  testTotalSumOfMethodDistances1(com.github.sevntu.checkstyle.analysis.OrderingTest)
  testTotalSumOfMethodDistances2(com.github.sevntu.checkstyle.analysis.OrderingTest)
  testDependencies(com.github.sevntu.checkstyle.analysis.OrderingTest)
  testRelativeOrderInconsistency(com.github.sevntu.checkstyle.analysis.OrderingTest)

Tests run: 28, Failures: 0, Errors: 27, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.977 s
[INFO] Finished at: 2016-06-28T15:19:20+03:00
[INFO] Final Memory: 11M/213M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project methods-distance-dsm: There are test failures.
[ERROR]
[ERROR] Please refer to C:\dev\projects\methods-distance\methods-distance-dsm\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### PR DESCRIPTION
**Pull request by alex-zuy**

### CODE REVIEW

**Comment by romani** [comment]
Strange, i do not see this could fix NPE

**Comment by alex-zuy** [comment]
File paths were stored as strings and were used as keys in map. This paths were generated in different places and in different ways. Values in map were stored using file paths containing forward slashes and then we attempted to obtain this values using file paths containing back-slashes leading to null being returned from Map.get.

**Comment by romani** [comment]
it become even more interesting, can you describe why this happening ? (different path in systems)

**Comment by alex-zuy** [comment]
A class that contains map of String(filePath) to Dependency pair was implemented as follows:
```java
    private static class DependencyInformationCollector implements DependencyInformationConsumer {

        private Map<String, Dependencies> filePathToDependencies = new HashMap<>();

        @Override
        public void accept(String filePath, Dependencies dependencies) {
            filePathToDependencies.put(filePath, dependencies);
        }

        public Dependencies getForFile(final String filePath) {
            return filePathToDependencies.get(filePath);
        }
    }
```
Method *accept(String,Dependencies)* gets invoked with absolute file path generated using java.io.File.getAbsolutePath() and thus puts it in map under this absolute path, which on Windows contains drive letter and back-slashes.
On the other hand, method *getForFile(String)* gets invoked with path generated using java.net.URL.getPath() and always contains forward slashes.

**Comment by romani** [comment]
ok, 
MethodCallDependencyCheck.java
```
final String inputFilePath = getFileContents().getFileName(); // AbsolutePath, checkstyle internal
dic.accept(inputFilePath, dependencies);
```

vs
MethodCallDependenciesCheckTestSupport.java
```
    protected Dependencies invokeCheckAndGetDependencies(final Configuration config, final String fileName) throws Exception {
        final String filePath = getInputPath(fileName); // getResource(fileName).getPath();// URL
        verify(config, filePath);
        return collector.getForFile(filePath);
```

so we need to fix that problem to have the same format of files. Keep them in system in different way is searching for problem.
I recommend to fix MethodCallDependencyCheck class and convert all paths to URL format , but keep them as String type.

**Comment by romani** [comment]
Ok, please squash commits to let me merge

**Comment by alex-zuy** [comment]
Squashed commits. Please, review.

**Comment by romani** [comment]
Why you add final in second file ?

**Comment by alex-zuy** [comment]
You probably wanted to ask why I added import of java.io.File. It was added by accidence. Fixed, please review.

**Comment by romani** [comment]
yes, please review commit yourself, before  sending it for review.

**Pull request merged**
