### PR TITLE
minor: remove redundant this (Issue checkstyle#7895)

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
major: (https://github.com/checkstyle/checkstyle/pull/11053)

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
@rnveach Kindly review my changes!

**Review by rnveach — APPROVED** [review]

**Comment by rnveach** [comment]
@romani I assume you agree with these changes since they follow the similar setup to `RequireThis`?

**Comment by rnveach** [comment]
@Rahulkhinchi03 I did not notice this, but commit message has to change. There is no issue 7895 in this repo.

I would use something like: `minor: remove redundant this (Issue checkstyle#7895)`.

**Comment by rnveach** [comment]
@Rahulkhinchi03 Just so it is clear, Issue title != Commit message.

**Comment by Rahulkhinchi03** [comment]
> 

I will keep this in mind, thanks @rnveach!

**Review by rnveach — CHANGES_REQUESTED** [review]
Still looking for commit message to change.

**Review by rnveach — APPROVED** [review]

**Comment by romani** [comment]
checkstyle issue is approved.

**Pull request merged**
